spring:
  application:
    name: jackpot-service
  datasource:
    url: jdbc:h2:mem:jackpotdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # Let's enable the console so you can inspect data
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true # Ensures schema is ready before data.sql runs
logging:
  level:
    org:
      apache:
        kafka: WARN
    kafka: WARN
    state: WARN
